### ISSUE TITLE
Tor progress indicator

### ISSUE THREAD

**Issue by cstiens** [guardianproject/poe#12]
@tladesignz I referenced this in issue #11, can this design of the progress indicator be implemented. 

Here are the specs:
green to show progress #7ED321
indicator line base color #000 with .24 alpha
height in the mockup is 4 px

<img width="359" alt="screenshot 2017-06-06 17 20 42" src="https://user-images.githubusercontent.com/1434597/26854622-9069a384-4adc-11e7-809f-aef8e0ac63c0.png">

The bigger idea behind this, is that the green line could be used as an indicator in any app that has Tor integrated (ex: Courier, FDroid) to show when the 'Tor Integrated' feature is turned on.

**Comment by tladesignz** [comment]
What about the progress in the ErrorViewController? Should we remove that? It doesn't make too much sense, in my opinion.

**Comment by tladesignz** [comment]
Also, we've got another problem. Modal view controllers have a translucent status bar and cover the whole screen:
![simulator screen shot 12 06 2017 11 44 26](https://user-images.githubusercontent.com/117089/27028622-9d2081e6-4f65-11e7-9707-87301da2d4f4.png)

**Comment by cstiens** [comment]
> What about the progress in the ErrorViewController? Should we remove that? It doesn't make too much sense, in my opinion.

Is the ErrorViewController, the red error screen? If so, I agree that we don't need it there.

**Comment by cstiens** [comment]
@tladesignz I have 2 possible options.
1) Make the progress bar thinner—2px instead of 4. That way, it wouldn't crowd the status bar info. Or
2) Move the indicator down so that it appears that it is below the status bar.

Thoughts? I think I would choose option 1, but am definitely open

Mockup of option 2
<img width="361" alt="screenshot 2017-06-16 13 44 44" src="https://user-images.githubusercontent.com/1434597/27240355-fb2d741a-5299-11e7-89bf-afb163dc0040.png">

**Comment by tladesignz** [comment]
@cstiens 
- Regarding the ErrorViewController: yes, and ok, I'll remove that progress bar there.
- I would rather argue for option 2: On scenes, which are embedded in a NavigationController (have a title and/or left and/or right buttons in the navigation bar), the status bar is part of the navigation bar. So there you would not be able to place that progress bar under the status bar. So, for reasons of symetry, I would prefer 2. Besides, the test image you provided looks good to me.

**Comment by cstiens** [comment]
2 sounds good! I assume that's what you did. :) Thanks!

**Comment by tladesignz** [comment]
@cstiens: Jup!
