### ISSUE TITLE
"Connecting" View

### ISSUE THREAD

**Issue by cstiens** [guardianproject/poe#2]
@tladesignz @mtigas @n8fr8 I have a couple ideas I'd like to explore for this view—

1) I'd like to fade the entire background from one shade of purple to another, back and forth, to give a 'pulsing' effect while the app is connecting to Tor. This would be a subtle way to make the app feel alive and working while the connection is being made. 
tla, Is this something that is implementable? :)

2) The other idea for this view is to make the characters in this illustration 'tappable' so that when you select one, it would tell you how that person uses Tor. Ex: "Normal people use Tor to protect their privacy..." These phrases would be pulled from the Tor website. Some of them may need to be tweaked a little bit to be more concise for mobile. We could even animate the character slightly (like nudging it up and back down) when it's selected. 
tla, Are there any challenges that you perceive in doing something like this?

![Image of Hello Loading](https://raw.githubusercontent.com/guardianproject/poe/master/UI-Mockups/05_Connectingv1.0.png)

![Image of Hello Loading](https://raw.githubusercontent.com/guardianproject/poe/master/UI-Mockups/05_Connectingv1.1.png)

**Comment by tladesignz** [comment]
ad 1) Should be doable without much problem. Memo to self:
http://stackoverflow.com/questions/3762561/how-to-animate-the-background-color-of-a-uilabel

ad 2) This is going to be a little more tricky:

- In order to have the characters jump up and down, I need everyone as a single, masked out, image.
- To have that image composition working on different screen sizes (from a 3.5" iPhone 4s in portrait to a 13" iPad Pro in landscape orientation) can get quite tricky. (Even if we would let go of the bouncing and wouldn't have masked-out single images.)
- Adding network traffic code for this kind of feature seems a little over the top to me.
- Last issue: Network traffic? Unobfuscated? A TOR network connection is not established at that point. That means, when a user taps a character, they will leak a network connection to a static address. If I were an opressive regime, I would reset all connections a client is currently doing, when that connection is triggered. @n8fr8: What's your take on this?

**Comment by cstiens** [comment]
Here are notes to document the discussion @tladesignz and I had regarding the design for this view.

1. The connecting view has multiple states:

- initial state ("Our diverse community...")

- a state for each character when tapped, which displays different text about how people use Tor.

- an error state, displayed when the app gets stuck in the progress for 'x' seconds and needs to be shut down and re-opened. @mtigas please confirm the time we should wait before asking the user to restart. (Note: the first thing to try if the app is not getting a connection to Tor, is to use a bridge. We should only show an error if the app absolutely has to be restarted to get Tor to work. @n8fr8 this is inline with the recommendations from the Tor UX research paper.)

2. The progress indicator behaves independent of everything on the screen. (The illustration interactions and progress indicator are not interdependent.)

3. The illustration will be designed to work on multiple screens—mobile portrait being the smallest; iPad landscape being the largest. The final illustration will have a ratio of about 1.5:4 to optimize for the ipad landscape view. It will be cropped starting on the left side at a 1:1 ratio to optimize for the mobile portrait view. There needs to be a decent amount of padding around the illustrated characters so that the interactive spots can be effectively and more simply implemented.

**Comment by cstiens** [comment]
We have initial illustrations from Vahid at Vivido! I'm getting clarity on whether he intends to merge them into one view or keep them separate. 

@tladesignz what is your opinion? I think these look quite nice separate. If they were kept this way, I imagine having the app cycle through the views while it's connecting. In addition, we could add a tap that would allow users to manually move to the next one.

![activists-sketch](https://user-images.githubusercontent.com/1434597/27240007-cba7dbdc-5298-11e7-9807-3ed384ad2780.png)
![bloggers-sketch](https://user-images.githubusercontent.com/1434597/27240008-cbabded0-5298-11e7-9c72-51d77b37e75d.png)
![business-people-sketch](https://user-images.githubusercontent.com/1434597/27240010-cbafec8c-5298-11e7-825b-2b6b4a5f06fa.png)
![facebook-sketch](https://user-images.githubusercontent.com/1434597/27240011-cbb013e2-5298-11e7-9d65-c93da83a7fe1.png)
![journalists-sketch](https://user-images.githubusercontent.com/1434597/27240009-cbaccb9c-5298-11e7-8a5c-25897d661ee4.png)
![people-sketch](https://user-images.githubusercontent.com/1434597/27240012-cbb3764a-5298-11e7-818d-6151369916c4.png)
![workers-sketch](https://user-images.githubusercontent.com/1434597/27240013-cbb86da8-5298-11e7-8997-fabb473cc922.png)

**Comment by n8fr8** [comment]
These are hilarious and lovely. I would love to have one with all the animals together. A group shot of some sort perhaps?

**Comment by tladesignz** [comment]
@cstiens I love them!
If we could all have them against transparent background, all issues about scaling, different device sizes and orientation would be off the table. Only the owl and the penguins images would need a slight rework to look good on all devices and orientations. Or we need more thinking on how to crop and size them right so they always work.

**Comment by cstiens** [comment]
> If we could all have them against transparent background, all issues about scaling, different device sizes and orientation would be off the table.

@tladesignz Do you mean if we have them against a transparent background and show them as separate images rather than one?

**Comment by tladesignz** [comment]
@cstiens Yeah, exactly. The pictures somewhat imply that, and also you did say so on your comment. :-)

**Comment by cstiens** [comment]
@tladesignz, I have .svg files for the illustrations in the connecting view. There will be 7 separate ones that we cycle through. I'm not sure which format you'd like, so I've attached the first image as a png @1x and @2x, and a pdf. The image is formatted so that you can position the bottom of the image at the bottom of the screen in portrait mode. I think that will work, but you probably have a better idea. Let me know! 

For landscape mode, I think we can scale the image down by 50% and position it at the bottom center. I will mock this up with the images to see if it works for them all. If not, I'll provide separate images for the landscape view. 

Lastly, the images will have transparent backgrounds so we can set the background color for each in the app. Each image will have a different background color.

![img-activitst copy 2x](https://user-images.githubusercontent.com/1434597/27445086-397fddae-573e-11e7-8756-a4515581eff3.png)

[img-activitst.pdf](https://github.com/guardianproject/poe/files/1095488/img-activitst.pdf)

![img-activitst](https://user-images.githubusercontent.com/1434597/27445087-3983ee6c-573e-11e7-9dfa-d76dbbae667f.png)

![img-activitst 2x](https://user-images.githubusercontent.com/1434597/27445088-3989037a-573e-11e7-8ebd-2b4ca6ac988e.png)

![img-activitst-full](https://user-images.githubusercontent.com/1434597/27445137-5880ebe4-573e-11e7-8a2c-1c566f3b8a10.png)

**Comment by tladesignz** [comment]
Yeah, that's nice. I like the idea and the pictures!

@cstiens The format which is best, would be a PDF containing vector graphics but with a defined target size in points. The point reference is the logical resolution of the devices, not the physical one. With all "Retina" devices, the physical resolution is double (in each direction) or even triple (on the "Plus" iPhones) of the logical resolution.

The Xcode IDE will then render the needed bitmap images on build, from this source files.

Please see these websites for reference:

http://iosres.com/
https://www.paintcodeapp.com/news/iphone-6-screens-demystified

BTW: Besides all this, the images still can be defined to display in a different (logical) size, which of course will introduce additional processing overhead and a theoretic haziness (or non-sharpness) :-) But that can normally be ignored, due to the enormous power, high resolution and small sizes of the screens, where this all operates in. One won't recognize a difference, normally.

**Comment by cstiens** [comment]
> The format which is best, would be a PDF containing vector graphics but with a defined target size in points.

@tladesignz Perfect. We can do PDFs containing vectors. Now I'm just wandering if it's best to give you images that are the full size of the screen or only part of the screen. Which is best for positioning—A or B? I read the link you sent, but it didn't seem to answer this question.

<img width="765" alt="screenshot 2017-06-23 09 12 23" src="https://user-images.githubusercontent.com/1434597/27485882-3a56d8de-57f4-11e7-83f9-333bafa195f1.png">

**Comment by tladesignz** [comment]
@cstiens Smaller than A. Only the box containing the images.
The vector graphics will be converted to bitmap, so even when the image is transparent, it will still be pixels which have to be stored. Transparent ones, but nevertheless pixels which eat up storage and especially RAM!

**Comment by cstiens** [comment]
Ok thanks!

**Comment by cstiens** [comment]
@tladesignz I've attached the single illustrations as .pdfs. The group and background colors are still to come.

[single-illustrations.zip](https://github.com/guardianproject/poe/files/1105340/single-illustrations.zip)

**Comment by tladesignz** [comment]
@cstiens I'm sorry, Carrie - I didn't express my self well enough... Can you please make the images in a box of the same size? Since they will get swapped with each other, they should nominally occupy the same screen estate, even if the real content is not exactly of the same size.

**Comment by cstiens** [comment]
Yep. No problem. That's what I was getting at with A. Since some of the images bleed to the side and/or bottom.

**Comment by cstiens** [comment]
@tladesignz Here they are—
[single-illustrations_same-size.zip](https://github.com/guardianproject/poe/files/1109988/single-illustrations_same-size.zip)

**Comment by cstiens** [comment]
Here are the background colors:
Group: 7D4698
Activist: 2196F3
People: CDEA52
Worker: 69D5A1
Journalist: FFCFBF
Business: FFDE2A
Facebook: 4A4A4A
Blogger: EE8B3C

**Comment by tladesignz** [comment]
First try with f99ae9a87e88b7c6c81333602f4a62b24648b6e3.

**Comment by cstiens** [comment]
@tladesignz Here's a screenshot showing which views need black text instead of white.
<img width="945" alt="screenshot 2017-07-05 23 08 55" src="https://user-images.githubusercontent.com/1434597/27895242-ece49360-61d6-11e7-8235-71497ee29e6e.png">

**Comment by cstiens** [comment]
Here's a version of the group photo that is not cropped on any side: [img-groupv2.pdf](https://github.com/guardianproject/poe/files/1126726/img-groupv2.pdf)

**Comment by cstiens** [comment]
@tladesignz I've asked our illustrator for a version of the owl that doesn't bleed to the edge. I'm going to wait to hear back and give you all of the final updated illustrations at once so you don't have to keep making updates.

**Comment by tladesignz** [comment]
@cstiens Fine by me!

**Comment by cstiens** [comment]
@tladesignz I've attached a zip file that contains all of the illustrations scaled appropriately so that there's not extra padding, and adjusted so that they do not bleed to any of the edges.

Also, please put these under this CC license: https://creativecommons.org/licenses/by-nc/2.0/
Thank you!!

[illustrationsv2-scaled.zip](https://github.com/guardianproject/poe/files/1136282/illustrationsv2-scaled.zip)

**Comment by tladesignz** [comment]
Great! Who's name should be mentioned for the artwork?
