### ISSUE TITLE
Test icon assets for iOS

### ISSUE THREAD

**Issue by cstiens** [guardianproject/poe#3]
Hi @tladesignz I've attached icon assets for the nav arrow in 4 different sizes as a .pdf format. Let me know if these work.

[ic_navigate.zip](https://github.com/guardianproject/poe/files/893836/ic_navigate.zip)

**Comment by tladesignz** [comment]
Great! @1x is enough, as long as it's a vector PDF (and not a bitmap). Xcode will render all needed versions automatically at build time.
