### ISSUE TITLE
Illustration sizing

### ISSUE THREAD

**Issue by cstiens** [guardianproject/poe#4]
@tladesignz I've put together some quick sketches of how the illustration could be sized for different devices. This is mainly to aid us in our discussion on Tuesday. The circles represent interaction points. 

<img width="893" alt="screenshot 2017-04-24 20 31 57" src="https://cloud.githubusercontent.com/assets/1434597/25364960/784d3072-292b-11e7-9ceb-5710ea6a9c59.png">
<img width="951" alt="screenshot 2017-04-24 20 32 07" src="https://cloud.githubusercontent.com/assets/1434597/25364962/7854ee8e-292b-11e7-9638-d64c441faa52.png">
<img width="898" alt="screenshot 2017-04-24 20 32 26" src="https://cloud.githubusercontent.com/assets/1434597/25364961/7854e3a8-292b-11e7-98ef-bf51f00b102f.png">
<img width="899" alt="screenshot 2017-04-24 20 32 45" src="https://cloud.githubusercontent.com/assets/1434597/25364963/785ba10c-292b-11e7-88df-0bf66a8ba40c.png">
<img width="863" alt="screenshot 2017-04-24 20 33 22" src="https://cloud.githubusercontent.com/assets/1434597/25364964/785c5688-292b-11e7-831e-2157f277baa1.png">

**Comment by cstiens** [comment]
I think these five devices capture the different needs.

<img width="787" alt="screenshot 2017-04-25 07 51 25" src="https://cloud.githubusercontent.com/assets/1434597/25385584/29c8e702-298a-11e7-8fc1-98d23976f117.png">

**Comment by tladesignz** [comment]
Good! Let's have some drafts and then I will try to make it work. We'll see, then, if there are problems, we didn't understand beforehand.

**Comment by cstiens** [comment]
Related to #2

**Comment by cstiens** [comment]
iPhone 7 Plus - 1920x1080
https://www.apple.com/iphone-7/specs/

Samsung S8 - 2960x1440
http://www.samsung.com/global/galaxy/galaxy-s8/specs/

iPad - 2048x1536
https://www.apple.com/ipad/specs

Android tablet
http://www.techradar.com/news/mobile-computing/tablets/15-best-android-tablets-in-the-world-1118205
Google Pixel - 2560 x 1800 
Huawei MediaPad M3 - 2560 x 1600
Nexus 9 - 2048 x 1536
