### ISSUE TITLE
Placeholder Illustration

### ISSUE THREAD

**Issue by cstiens** [guardianproject/poe#6]
@tladesignz I've attached a placeholder image to use temporarily for the connecting view illustration.

![iphone-1080x1220-light](https://cloud.githubusercontent.com/assets/1434597/25702476/c155cd8e-3096-11e7-80e7-a2470dfdcf2a.png)

**Comment by tladesignz** [comment]
As discussed in the weekly call an hour ago: I'll wait for an improved version or alternatively the decision to go without for now.

Please give this issue back, when done!
