### ISSUE TITLE
Design launch icon

### ISSUE THREAD

**Issue by cstiens** [guardianproject/poe#8]

**Comment by cstiens** [comment]
@tladesignz Working on it. Will plan to have it for next Thursday's scrum, June 22.

**Comment by cstiens** [comment]
Here's a mockup of an app icon for Onion Browser. @mtigas @n8fr8 @tladesignz Let me know what you think. It's the one above 'Your App'

<img width="424" alt="screenshot 2017-06-21 13 27 38" src="https://user-images.githubusercontent.com/1434597/27400397-9447641e-5685-11e7-80e7-0cafbe772ebd.png">

**Comment by tladesignz** [comment]
@cstiens I like the icon a lot, but I'm not too happy with the white background. Unfortunately I don't have a good solution to this, either. Black will be too dark. What's a good contrasting color or color gradient for purple?
And the edges of the circle look rough. But I guess that's just because of the preview?

**Comment by n8fr8** [comment]
I think there should be some other design element that indicates this is a browser. Not sure what that is, but the O alone seems plain. Also, the plain white bothers me a bit as well. Can we do a gradient of some kind?

**Comment by cstiens** [comment]
Thank you for the feedback @n8fr8 and @tladesignz!

I agree about the white background. It's not super great. I've tried a purple gradient as well as yellow and green gradients for the background. But, none of them look quite right to me. I'm going to work with it a little more. So far, the dark purple background looks the best—

<img width="425" alt="screenshot 2017-06-23 14 00 49" src="https://user-images.githubusercontent.com/1434597/27496627-63b74286-581c-11e7-95d3-001f53dfd8f8.png">

> And the edges of the circle look rough. But I guess that's just because of the preview?

Yes, that was just the preview.

> I think there should be some other design element that indicates this is a browser. Not sure what that is, but the O alone seems plain. 

Here's a line-up of the most commonly used web browsers—
The themes I see are a circular motion, symbology of the globe and navigation. The simple 'o' doesn't bother me. I like simplicity. But, I can certainly brainstorm more options. In the meantime, I've provided the logo from the mockup above, so that we have something that is inline with the Poe design to work with and try out. (It's too big to attach here, so I'll put it elsewhere in the repo.)

![image](https://user-images.githubusercontent.com/1434597/27496729-d49df09e-581c-11e7-9a14-df497140a16e.png)

There's also Duckgo and Brave browser—
The obvious theme is animals. ;) Well, they have their own brand story they are telling, so their characters work for them, I suppose.
![image](https://user-images.githubusercontent.com/1434597/27496790-27fbb258-581d-11e7-8bcc-dded2c698cd1.png)

![image](https://user-images.githubusercontent.com/1434597/27496802-30882fd2-581d-11e7-88cb-3c4ca9a363a5.png)

**Comment by n8fr8** [comment]
I think the plain O may be too close to Opera. I think we should go for a fusion of the two perhaps - the O plus a little bit of the Chrome design elements?

I also want to keep it light as possible. We have our colorful POE on boarding, though it is that beautiful purple shade. We have to avoid the whole "Dark Web" aesthetic as much as we can.

Thanks!

**Comment by cstiens** [comment]
> I also want to keep it light as possible. We have our colorful POE on boarding, though it is that beautiful purple shade. We have to avoid the whole "Dark Web" aesthetic as much as we can.

Nate, do you think the dark purple background feels like the 'dark web'?

**Comment by cstiens** [comment]
Again, I'll continue to work on options, but here's the latest if we want to use it. I know we're getting close to the release.

[ob_app-icon_1024x1024.pdf](https://github.com/guardianproject/poe/files/1098874/ob_app-icon_1024x1024.pdf)

**Comment by tladesignz** [comment]
Since I added the logo weeks ago and there is no active discourse about it anymore, I assume, this is safe to be closed.
