### ISSUE TITLE
Design splash/loading screen

### ISSUE THREAD

**Issue by cstiens** [guardianproject/poe#9]

**Comment by cstiens** [comment]
@tladesignz I'm thinking this will be very simple—A solid background with the app logo on top. Once I get the app logo finalized, I'll provide specs for it.

Did you have any other ideas for it?

**Comment by tladesignz** [comment]
@cstiens Nope. I guess, that's fine. We should just make sure, that there's no jumpy behaviour because of different colors or stuff that's first on the splash screen and later on the first scene of POE.

**Comment by cstiens** [comment]
Waiting for feedback on the app logo, but this is what the launch screen would look like with the proposed logo.

![00 0_load](https://user-images.githubusercontent.com/1434597/27401847-54e93b3a-568a-11e7-8e87-dcb8df8a1223.png)

**Comment by tladesignz** [comment]
Nice!

**Comment by tladesignz** [comment]
@cstiens Thanks for bringing that up again! I will implement it, but I would need the pure logo on transparent background. Can you post that as PDF here or attach to the source?

**Comment by cstiens** [comment]
@tladesignz Here you go!
[ob_transparent_logo_trans.pdf](https://github.com/guardianproject/poe/files/1113216/ob_transparent_logo_trans.pdf)

**Comment by tladesignz** [comment]
Since I added this weeks ago and there is no dispute about the logo anymore, I assume this to be safe to close.

**Comment by n8fr8** [comment]
This is fine for now... I do think the purple on purple is a bit dark overall, as is the purple on black dark launcher icon. I can talk to Carrie directly about this, and we can reopen if we find something better.
